try{
    console.log(naExisto)
}catch(err){
    console.log(nao naExisto)
}